version_id: 7.9
id: rhel
instance:
  create:
    image-name: ibm-redhat-7-9-minimal-amd64-3
    network_name: sn-01-cephqe-pvt-network
    private_key: ibmc-shared
    group_access: cephqe-sec-grp-all-access
    profile: bx2-2x8


  setup:  |
    #cloud-config
    ssh_pwauth: True
    groups:
      - cephuser
    users:
      - name: cephuser
        primary-group: cephuser
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
        ssh-authorized-keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyaKj0phxJTD2ZblCbujHOlH3KWx4WlEUdKWxftfBarFbN9tztClUXC4WtSDXsJeith9/JaiXkJMNulSEmZ1+WfpaS1CKiBxyy/6lzwaiqnphiIJIZu7mQTOydcc0ACIE1g/sm0yBpOQRaa28BFAlQxN5IFVzQqws1M3uSYU9iyOj8CZagnavIHMPfw7wOVX+ncUl+YIySRgsjbtrLPm1cfEcutpT8SphNOu6mKDq5jN9jVqn5j+2KxAmJRjkKmEyNXrzhTUgdBrxfJ877JkeyNfjzaptX29ms1LzJxVPV0pitJ7gHirc3LlZ8PihIdWR52Ts2BwcF86/2CB39nw+NCXSICbGmWues0m5BjIC7utGERA/fU5eE7CnTKFuUaONkL7CGqQN/7bak0E9IUJqzyRswDub93j9QyXfV305wHF4nfOeHLDKbcQHgLM1/rjs6BQMZvJlS+f+2kJHMfFD9UYCrnhdMpLXTvJ8amlF9J+HUhu7zLPNuEjJf9I4aNb0= psathyan@psathyan.remote.csb
    chpasswd:
      list: |
        root: Welcome123#
        cephuser: pass123
      expire: False
    runcmd:
      - yum install -y yum-utils sudo
      - sed -i -e 's/^Defaults\s\+requiretty/# \0/' /etc/sudoers
      - curl -k -o /etc/pki/ca-trust/source/anchors/ceph-qe-ca.pem https://10.245.4.4/.ceph-qe-ca.pem
      - curl -k -o /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt https://10.245.4.4/.RH-IT-Root-CA.crt
      - update-ca-trust
      - subscription-manager unregister
      - rpm -e katello-ca-consumer-rhncapsyd0102.service.networklayer.com-1.0-4.noarch
      - subscription-manager clean
      - rm -f /etc/pki/ca-trust/source/anchors/katello-server-ca.pem
      - touch /ceph-qa-ready
